-- ============================================================
-- AI-CDIO — Schema v9: Narrative + path-to-next-level on scores
--
-- Phase 1C Day 9 (2026-05-06). Two new columns on module_scores:
--
--   narrative           text — 3-4 sentence prose explanation of why
--                              the stakeholder landed at this maturity
--                              level, written like a CDIO would write
--                              it (not the spreadsheet evidence string).
--
--   path_to_next_level  jsonb — array of { action, source } objects.
--                              Three concrete actions that lift the
--                              stakeholder's view from current_level →
--                              current_level + 1, each sourced from
--                              the playbook RAG or the framework
--                              citation on the question itself.
--
-- Both nullable so legacy rows + N/A rows continue to work. The
-- assessment route populates them when a stakeholder finishes a
-- module. NULL means "narrative not yet generated" (which the UI
-- can render as the legacy short evidence string).
--
-- Idempotent — safe to re-run.
-- ============================================================

alter table module_scores
  add column if not exists narrative text;

alter table module_scores
  add column if not exists path_to_next_level jsonb not null default '[]'::jsonb;

comment on column module_scores.narrative is
  'Phase 1C: 3-4 sentence prose explanation of the score, generated by the assessment agent. Reads like a CDIO would write it. NULL on legacy rows + N/A rows.';

comment on column module_scores.path_to_next_level is
  'Phase 1C: array of { action, source } objects describing 3 concrete steps that move this stakeholder''s view from current_level to current_level + 1. Empty array on legacy rows, N/A rows, and Level 5 rows (no next level).';
